name: "BMS Pace - Multi bms"
description: "Pace BMS Interface"
version: "2.5"
slug: "bms_pace_multi"
url: "https://github.com/johblack18/bmspace/blob/main/pace-bms-dev"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

uart: true
usb: true

options:
  mqtt_host: "10.0.0.64"
  mqtt_port: 1883
  #mqtt_user: "mqtt-users"
  #mqtt_password: "mqtt-users"
  mqtt_ha_discovery: true
  mqtt_ha_discovery_topic: "homeassistant"
  mqtt_base_topic: "bmspace"
  connection_type: "IP"
  bms_ip: "10.0.0.10"
  bms_port: 998
  bms_serial: "/dev/ttyUSB0"
  scan_interval: 5
  debug_output: 0
  force_pack_offset: 0
  zero_pad_number_cells: 0
  zero_pad_number_packs: 0
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  mqtt_ha_discovery: bool
  mqtt_ha_discovery_topic: str
  mqtt_base_topic: str
  connection_type: list(IP|Serial)
  bms_ip: str
  bms_port: int
  bms_serial: str
  scan_interval: int
  debug_output: int
  force_pack_offset: "int?"
  zero_pad_number_cells: "int?"
  zero_pad_number_packs: "int?"
